package lab8.Client.VehicleCollectionClient.Resources;

import java.util.ListResourceBundle;

public class Labels_ru extends ListResourceBundle {
    public Object[][] getContents() {return contents;}
    private Object[][] contents = {
            {"menuFile", "Файл"},
            {"menuCollection", "Коллекция"},
            {"menuHelp", "Помощь"},
            {"menuFileChangeLang", "Сменить язык"},
            {"menuFileExit", "Закрыть"},
            {"menuServer", "Сервер"},
            {"menuServerConnect", "Подключиться"},
            {"menuServerLogIn", "Войти"},
            {"menuServerRegister", "Зарегестрироваться"},
            {"menuCollectionInfo", "Информация"},
            {"menuCollectionAdd", "Добавить транспорт"},
            {"menuCollectionSort", "Сортировка"},
            {"menuCollectionSortByType", "По типу"},
            {"menuCollectionSortByName", "По имени"},
            {"menuCollectionSumOfWheels", "Сумма всех колёс"},
            {"menuHelpAbout", "О приложении"},

            {"aboutAppWindow", "О приложении"},
            {"informationAboutApp", "Это приложение для операций с коллекцией транспортных средств, расположенной на удалённом сервере.\nРазработчик: ilust"},
            {"connectToServerWindow", "Подключиться к серверу"},
            {"logInWindow", "Войти в учётную запись"},
            {"registerWindow", "Зарегистрироваться"},
            {"collectionInformationWindow", "Информация о коллекции"},
            {"sumOfWheelsWindow", "Сумма колёс в коллекции"},

            {"connectionStatusLabel", "Статус подключения"},
            {"tableInfoLabel", "Информация о таблице"},
            {"tableInfoShowing", "Отображается"},
            {"tableInfoVehiclesFrom", "транспортных средств из"},
            {"tableInfoInCollection", "в коллекции"},

            {"emptyTable", "Нет транспортных средств"},
            {"idColumn", "ID"},
            {"keyColumn", "Ключ"},
            {"userColumn", "Пользователь"},
            {"nameColumn", "Имя"},
            {"coordinatesColumn", "Координаты"},
            {"coordinatesXColumn", "X"},
            {"coordinatesYColumn", "Y"},
            {"dateColumn", "Дата"},
            {"enginePowerColumn", "Мощность"},
            {"numberOfWheelsColumn", "Количество колёс"},
            {"capacityColumn", "Вместимость"},
            {"typeColumn", "Тип"},
            {"addVehicleButton", "Добавить транспорт"},
            {"attention", "Внимание"},
            {"closeApp", "Закрыть приложение"},

            {"enterIpAndPort", "Введите IP и порт сервера"},
            {"cancelButton", "Отмена"},
            {"connectButton", "Подключиться"},
            {"error", "Ошибка"},
            {"unableToConnect", "Не удалось подключиться, попробуйте снова"},
            {"connected", "подключен к серверу"},
            {"notConnected", "не подключен"},
            {"errorWhileReceivingCollection", "Ошибка при получении коллекции от сервера"},
            {"connectionLost", "Соединение с сервером потеряно"},

            {"user", "Пользователь"},
            {"password", "Пароль"},
            {"loginButton", "Войти"},
            {"cancelButton", "Отмена"},
            {"unableToLogIn", "Ошибка при входе"},
            {"authorizedAs", "авторизован как"},

            {"find", "Найти"},
            {"in", "в"},
            {"idColumnFilter", "ID (совпадает)"},
            {"nameColumnFilter", "Имя (содержит)"},
            {"keyColumnFilter", "Ключ (начинается с)"},

            {"mapLabelHint", "Выберите транспорт"},
            {"mapLabelVehicleID", "Транспорт: ID"},
            {"mapLabelVehicleKey", "ключ"},
            {"mapLabelVehicleName", "имя"},

            {"wrongInput", "Неверный ввод"},
            {"canNotBeNull", "Это значение не может быть null"},
            {"canNotBeNegative", "Это значение должно быть больше нуля"},
            {"canNotBeNullOrEmpty", "Это значение не может быть null или пустым"},
            {"canNotBeNullOrNegative", "Это значение не может быть null и должно быть больше нуля"},
            {"mustBeOnOfTypes", "Тип должен быть одним из:\n BICYCLE, BOAT, DRONE, HELICOPTER, HOVERBOARD"}};
}
